11.15. Надо подкачаться / 2  Получение и отправка данных
htmlacademy-javascript/2131065-keksobooking-26 pull request #12
Opened 2022-09-04 14:13 UTC by n0izzzz

По прежнему не понимаю как добиться этого пункта:

> _Обратите внимание, что ошибка загрузки данных влияет на отображение меток и их фильтрацию, но не влияет на отправку формы. Даже если данные для меток не загрузились, возможность выбрать адрес на карте и отправить форму сохраняется._

![image](https://user-images.githubusercontent.com/106422902/188317899-f788ca13-fe5c-4e5e-9ba4-ec021ebcbfd6.png)

Помимо этого вроде бы все работает, ошибки обрабатываются, сообщения показываются.

2022-09-04 19:35 UTC, o-bender requested changes

2022-09-04 19:35 UTC, o-bender commented on js/main.js
> +getData(initMap, showErrorMessageTimer);
относительно твоего вопроса
```
getData(initMap, () => {
  showErrorMessageTimer();
  initMap([]);
);
```

2022-09-04 19:35 UTC, o-bender commented on js/tools.js
> +const removeItem = (item) => {
Функция вызывающая метод? Какую задачу она решает?

2022-09-04 19:35 UTC, o-bender commented on js/tools.js
> +const closeMessage = (item) => {
Некорректное название т.к. функция не закрывает сообщение.

2022-09-04 19:35 UTC, o-bender commented on js/tools.js
> +  document.querySelector(item).onclick = function () {
Правильней будет использовать addEventListener

2022-09-04 19:35 UTC, o-bender commented on js/tools.js
> +  document.querySelector(item).onclick = function () {
Функцию можно и нужно заменить на стрелочную

2022-09-04 19:35 UTC, o-bender commented on js/tools.js
> +  document.querySelector(item).onclick = function () {
Функция должна принимать evt

2022-09-04 19:35 UTC, o-bender commented on js/tools.js
> +    removeItem(document.querySelector(item));
Из evt можно получить target и уйти от повторного вызова querySelector

2022-09-04 19:35 UTC, o-bender commented on js/tools.js
> +    if (evt.keyCode === 27) {
Через неделю ты забудешь что за 27.

2022-09-04 19:35 UTC, o-bender commented on js/tools.js
> +  window.onkeydown = (evt) => {
Правильней будет использовать addEventListener и удалять слушатель после срабатывания события.

2022-09-04 19:35 UTC, o-bender commented on js/tools.js
> +  document.querySelector('.ad-form').reset();
это `document.querySelector('.ad-form')` надо вынести в переменную в области видимости модуля.

2022-09-04 19:35 UTC, o-bender commented on js/tools.js
> +  divMessage.innerHTML = text;
Не надо использовать innerHTML. Особенно когда ты не контролируешь содержимое переменной text. Фактически там может быть что угодно. И если ты или твой коллега используют её не аккуратно, то это будет xss уязвимость.

2022-09-04 19:35 UTC, o-bender commented on js/tools.js
> +  }, 2000);
хардкод

2022-09-05 17:11 UTC, n0izzzz commented on js/main.js
> +getData(initMap, showErrorMessageTimer);
Сделал, получилось, но не понял.

2022-09-05 17:21 UTC, n0izzzz commented on js/tools.js
> +  divMessage.innerHTML = text;
Поменял на `textContent`

2022-09-05 17:33 UTC, n0izzzz commented on js/tools.js
> +  }, 2000);
Добавил кнопку "Обновить страницу", и возможность закрыть сообщение по ESC и клику на любом месте кроме кнопки.

2022-09-05 17:44 UTC, n0izzzz commented on js/tools.js
> +const removeItem = (item) => {
Убрал.

2022-09-05 17:46 UTC, n0izzzz commented on js/tools.js
> +const closeMessage = (item) => {
Переименовал в `removeMessage`

2022-09-05 18:38 UTC, n0izzzz commented on js/tools.js
> +  document.querySelector(item).onclick = function () {
> Правильней будет использовать addEventListener
Сделал

> Функцию можно и нужно заменить на стрелочную
Сделал

> Функция должна принимать evt
Не понял куда и для чего

2022-09-05 19:17 UTC, n0izzzz commented on js/tools.js
> +  window.onkeydown = (evt) => {
Сделано.

2022-09-05 19:17 UTC, n0izzzz commented on js/tools.js
> +    if (evt.keyCode === 27) {
Поменял на `evt.key === 'Escape'`

2022-09-05 19:35 UTC, n0izzzz commented on js/tools.js
> +  document.querySelector('.ad-form').reset();
Готово.

2022-09-05 19:37 UTC, n0izzzz commented on js/tools.js
> +    removeItem(document.querySelector(item));
Сначала сделал так, но потом вернул как было, так как по клику удалялись элементы, которые не нужно удалять )
![image](https://user-images.githubusercontent.com/106422902/188505876-ebf81f64-36d8-4e48-841f-801f7b6f9148.png)

2022-09-05 20:11 UTC, merged