Module4 task1
htmlacademy-javascript/2131065-keksobooking-26 pull request #4
Opened 2022-08-09 19:33 UTC by n0izzzz

2022-08-09 20:31 UTC, o-bender requested changes

2022-08-09 20:31 UTC, o-bender commented on js/main.js
> +    avatar: '',
С аватаром как-то непропорционально сложно. Array.from принимает два аргумента: первый что-то с атрибутом length, и второй это callback. callback в свою очередь тоже принимает два аргумент: первый это элемент из списка, в нашем случае undefined и нам он не нужен. И второй аргумент порядковый номер элемента. И вот его можно использовать как id для фотографии. Или можно просто брать случайное число из диапазона чисел.

2022-08-09 20:31 UTC, o-bender commented on js/main.js
> +    address: `lat: ${getRandomFloatNumber(35.65000, 35.70000, 5)}, lng: ${getRandomFloatNumber(139.70000, 139.80000, 5)}`,
address должен содержать только координаты и запятую разделяющую их.

2022-08-09 20:31 UTC, o-bender commented on js/main.js
> +    if (i < 9) {
можно использовать метод .padStart(2, '0') что бы избежать конструкции с if

2022-08-11 11:16 UTC, n0izzzz commented on js/main.js
> +    avatar: '',
Взял случайное число от 1 до 9 (чтобы избежать истории с нулем у 10 и лишних конструкций), так можно?

2022-08-11 19:15 UTC, merged