7.15. Отрисуй меня полностью (часть 1)
htmlacademy-javascript/2131065-keksobooking-26 pull request #6
Opened 2022-08-15 15:32 UTC by n0izzzz

2022-08-15 18:48 UTC, o-bender requested changes
Пересмотри консультацию за 11.08. В этом PR-е очень много шагов, которые я объяснял почему и как не надо делать и как делать надо.

2022-08-15 18:48 UTC, o-bender commented on js/generate-similar-objects.js
> +let objectFragment = document.createDocumentFragment();
1. Я на консультации говорил, что DocumentFragment надо создавать внутри функции. Только на тот момент пока он необходим.
2. А он вообще тут зачем? В 29 строке туда записывается клон objectTemplate.

2022-08-15 18:48 UTC, o-bender commented on js/generate-similar-objects.js
> +  adsData.forEach(({ author, offer }) => {
1. Цикл не нужен. Функция должна создавать и **возвращать 1**  popup.
2. Даже не смотря на цикл в dom будет добавлен всего один popup. И хоть это в итоге даёт верный результат, но это результат бага.

2022-08-15 18:48 UTC, o-bender commented on js/generate-similar-objects.js
> +    const addSrc = (objectFragmentClass, adsDataElement) => {
Не надо объявлять вложенные друг в друга функции. Да, можно использовать стрелочные анонимные функции, на пример, для установки слушателей. Но и только.
Функция должна читаться как предложение. Чем сложней предложение тем сложней его понять.

2022-08-15 18:48 UTC, o-bender commented on js/generate-similar-objects.js
> +    const getOfferType = (type) => offerTypes[type];
В этой функции просто нет необходимости. Она ничего не делает.

2022-08-15 18:48 UTC, o-bender commented on js/generate-similar-objects.js
> +    getOfferTextContent('.popup__text--capacity', `${offer.rooms} комнаты для ${offer.guests} гостей`);
В такой ситуации:
```
offer = {
    rooms: undefined,
    guests: undefined,
};
getOfferTextContent('.popup__text--capacity', `${offer.rooms} комнаты для ${offer.guests} гостей`);
```
мы увидим на экране `undefined комнаты для undefined гостей`

2022-08-15 18:48 UTC, o-bender commented on js/generate-similar-objects.js
> +    getOfferTextContent('.popup__text--price', `${offer.price} ₽/ночь`);
Если offer.price будет undefined, то увидим на экране `undefined  ₽/ночь`

2022-08-15 18:48 UTC, o-bender commented on js/generate-similar-objects.js
> +  if (adsDataElement === undefined || adsDataElement.includes('undefined')) {
Странная функция со странным условием.
```
isNull([123, undefined, 321]) // вернёт undefined
isNull([]) // вернёт undefined
isNull([123, 'undefined', 321]) // вернёт true
```
Предполагаю, что это попытка найти слово undedined в строке. Это называется костыль. Когда пытаешься уже написанный код подпереть неудачным решением. А если в строке будет не undefined, а null?
В общем так делать не надо. Надо проверять сами данные, а не результат работы с ними.
Т.е. надо проверять не `${offer.price} ₽/ночь`, а `offer.price`.

2022-08-15 18:48 UTC, o-bender commented on js/generate-similar-objects.js
> +const adsData = getSimilarAds();
Эта функция должна вызываться в main.js.

2022-08-15 20:06 UTC, n0izzzz commented on js/generate-similar-objects.js
> +    getOfferTextContent('.popup__text--price', `${offer.price} ₽/ночь`);
Нет, не увидим. Если будет  undefined, то элемент скроется:

![image](https://user-images.githubusercontent.com/106422902/184709380-87e71abd-7117-46f9-bb29-aa753e6f6388.png)

2022-08-15 20:14 UTC, n0izzzz commented on js/generate-similar-objects.js
> +    getOfferTextContent('.popup__text--capacity', `${offer.rooms} комнаты для ${offer.guests} гостей`);
Тоже работает, undefined не выводит:

![image](https://user-images.githubusercontent.com/106422902/184710387-527d2f9a-e705-42cd-9f7e-84de0f742160.png)

2022-08-16 08:06 UTC, o-bender commented on js/generate-similar-objects.js
> +    getOfferTextContent('.popup__text--price', `${offer.price} ₽/ночь`);
Это потому что функция isNull это шаткий костыль подпирающий логику getOfferTextContent и `${offer.price} ₽/ночь`.

2022-08-16 19:32 UTC, n0izzzz commented on js/generate-similar-objects.js
> +let objectFragment = document.createDocumentFragment();
Убрал

2022-08-16 19:33 UTC, n0izzzz commented on js/generate-similar-objects.js
> +  adsData.forEach(({ author, offer }) => {
Сделал

2022-08-16 19:33 UTC, n0izzzz commented on js/generate-similar-objects.js
> +    const addSrc = (objectFragmentClass, adsDataElement) => {
Разнес

2022-08-16 19:33 UTC, n0izzzz commented on js/generate-similar-objects.js
> +    const getOfferType = (type) => offerTypes[type];
Поправил

2022-08-16 19:33 UTC, n0izzzz commented on js/generate-similar-objects.js
> +    getOfferTextContent('.popup__text--capacity', `${offer.rooms} комнаты для ${offer.guests} гостей`);
Пофиксил

2022-08-16 19:34 UTC, n0izzzz commented on js/generate-similar-objects.js
> +    getOfferTextContent('.popup__text--price', `${offer.price} ₽/ночь`);
Укрепил костыль )

2022-08-16 19:34 UTC, n0izzzz commented on js/generate-similar-objects.js
> +  if (adsDataElement === undefined || adsDataElement.includes('undefined')) {
Улучшил

2022-08-16 19:35 UTC, n0izzzz commented on js/generate-similar-objects.js
> +const adsData = getSimilarAds();
Вынес

2022-08-17 08:18 UTC, o-bender requested changes

2022-08-17 08:18 UTC, o-bender commented on js/generate-similar-objects.js
> +    hideElement(objectTemplate.querySelector(`${objectFragmentClass}`));
а почему нельзя просто `querySelector(objectFragmentClass)`?

2022-08-17 08:18 UTC, o-bender commented on js/generate-similar-objects.js
> +    objectTemplate.querySelector(`${objectFragmentClass}`).src = adsDataElement;
а почему нельзя просто `querySelector(objectFragmentClass)`?

2022-08-17 08:18 UTC, o-bender commented on js/generate-similar-objects.js
> +const adsData = getSimilarAds();
Давай ещё раз перечитаем, что я написал: функция должна вызываться в main.js. 
Вызов функции это getSimilarAds(), т.е. когда ты у пишешь имя функции и круглые скобки. Так что смысл в том что бы всю эту строку перенести в main.js.

2022-08-17 08:18 UTC, o-bender commented on js/generate-similar-objects.js
> +let objectTemplate = '';
Давай ещё раз. Так делать не надо. Не надо создавать какую-то переменную, в модуле, а потом обращаться к ней из разных функций. Тем более что нет необходимости в таком шаге. Ни что не мешает тебе передавать явно этот элемент внутрь функций.
```
const getPopup = (data) => {
  const objectTemplate = document.querySelector('#card').content;
  addSrc(objectTemplate, '.popup__avatar', data.author.avatar);
  getOfferTextContent(objectTemplate, '.popup__title', data.offer.title);
  getOfferTextContent(objectTemplate, '.popup__text--address', data.offer.address);
  // и т.д.
```

2022-08-17 08:18 UTC, o-bender commented on js/generate-similar-objects.js
> +const getOfferTextContent = (objectFragmentClass, adsDataElement) => {
Дублируешь objectTemplate.querySelector. Само по себе это не проблема. Но только когда надо будет, изменить способ получения dom элемента, придётся опять это дублировать. Правильней будет так:
```
const getOfferTextContent = (objectFragmentClass, adsDataElement) => {
  const element = objectTemplate.querySelector(objectFragmentClass);
  if (element) {
    if (isNull(adsDataElement)) {
      hideElement(element);
    } else {
      element.textContent = adsDataElement;
    }
  }
};
```

2022-08-17 18:14 UTC, n0izzzz commented on js/generate-similar-objects.js
> +let objectTemplate = '';
Сделано

2022-08-17 18:16 UTC, n0izzzz commented on js/generate-similar-objects.js
> +    hideElement(objectTemplate.querySelector(`${objectFragmentClass}`));
Чёт перемудрил :)
Пофиксил.

2022-08-17 18:21 UTC, n0izzzz commented on js/generate-similar-objects.js
> +const getOfferTextContent = (objectFragmentClass, adsDataElement) => {
Согласен. Поправил.

2022-08-17 18:52 UTC, merged